version: '2'
services:

#  php:
#    image: php:8.2-apache
#    container_name: php
#    hostname: future.test
#    volumes:
#      - ./:/var/www/html

  webserver:
    container_name: PHP-webserver
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - '8000:80'
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 951753
      MYSQL_DATABASE: future
      MYSQL_USER: admin
      MYSQL_PASSWORD: 951753
    ports:
      - "6000:3306"